# Generated by Django 2.2.6 on 2022-01-15 21:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='created',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 15, 21, 27, 0, 82414), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
