# Generated by Django 2.2.16 on 2022-01-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220115_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 16, 13, 43, 14, 664078), verbose_name='Дата комментария'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
