# Generated by Django 2.2.16 on 2022-01-16 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220116_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='created',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 16, 16, 40, 25, 764793), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
