# Generated by Django 2.2.16 on 2022-01-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220116_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
