# Generated by Django 2.2.16 on 2022-01-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_commentmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments/', verbose_name='Изображение'),
        ),
    ]
