# Generated by Django 2.2.16 on 2022-01-24 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Аноним', help_text='Введите имя.', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default='Анонимов', help_text='Введите фамилию.', max_length=50, verbose_name='Фамилия')),
                ('experience', models.CharField(default='0', help_text='Введите свой стаж.', max_length=10, verbose_name='Стаж работы')),
                ('year_of_release', models.CharField(default='1812', help_text='Введите год выпуска.', max_length=10, verbose_name='Год выпуска')),
                ('city', models.CharField(default='Забугоровск', help_text='Введите свой город.', max_length=10, verbose_name='Город проживания')),
                ('kogorta', models.CharField(default='0', help_text='Введите свою когорту.', max_length=30, verbose_name='Когорта')),
                ('image', models.ImageField(blank=True, upload_to='user_profile/', verbose_name='Изображение')),
                ('information', models.TextField(default='Я просто посмотреть зашёл.', verbose_name='Краткая информация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
