# Generated by Django 2.2.16 on 2022-01-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20220124_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='0', help_text='Введите что-нужно', max_length=50, verbose_name='Поиск')),
            ],
        ),
    ]
