# Generated by Django 2.2.16 on 2022-01-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_searchpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpost',
            name='text',
            field=models.CharField(help_text='Введите что-нужно', max_length=50, verbose_name='Поиск'),
        ),
    ]
