# Generated by Django 2.2.16 on 2022-01-24 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20220124_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
    ]
