# Generated by Django 2.2.16 on 2022-01-25 20:33

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20220124_1855'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='ban on signing',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='uning_fields'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='prevent_follows'),
        ),
    ]
