# Generated by Django 2.2.16 on 2022-01-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20220125_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments/', verbose_name='Изображение'),
        ),
    ]
